# Use the official PostgreSQL image
FROM postgres:latest

# Environment variables to set up the initial database
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD root
ENV POSTGRES_DB PavanDB

# Expose the PostgreSQL port
EXPOSE 5432


# Add CMD to wait for the database and then start PostgreSQL
